/* generated from model null*/
/* generated by template symboltable.ModelNameCalculator*/

package de.monticore.lang.od._symboltable;

import com.google.common.collect.ImmutableSet;
import de.se_rwth.commons.Names;

import java.util.Collections;
import java.util.Set;

public class ODModelNameCalculator extends ODModelNameCalculatorTOP {

  @Override
  protected Set<String> calculateModelNamesForODObject(String name) {
    // e.g., if p.OD.Object, return p.OD
    if (!Names.getQualifier(name).isEmpty()) {
      return ImmutableSet.of(Names.getQualifier(name));
    }

    return Collections.emptySet();
  }
}
