/* generated from model null*/
/* generated by template symboltable.ModelNameCalculator*/

package de.monticore.lang.od._symboltable;

public class ODModelNameCalculator extends ODModelNameCalculatorTOP {


}
