# (c) https://github.com/MontiCore/monticore

image: maven:3.5.4-jdk-8-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode"

cache:
  paths:
    - .gradle/wrapper
  key: ${CI_COMMIT_REF_SLUG}

before_script:
  - chmod +x gradlew
  - chmod +x check/downloadlinkchecker.sh
  - chmod +x check/mdlinkcheck.sh
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - deploy
  - check

build:
  stage: build
  script:
    - "./gradlew assemble --refresh-dependencies $GRADLE_OPTS $ARGS1"
  artifacts:
    paths:
      - "."
    expire_in: 1 week

test:
  stage: test
  dependencies:
    - build
  script:
    - "./gradlew check $GRADLE_OPTS $ARGS2"

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - "./gradlew publish $GRADLE_OPTS $ARGS3 -PmavenPassword=$password -PmavenUser=$username"
  only:
    - master
    - dev

checkMDLinks:
  stage: check
  dependencies:
    - test
  script:
    - "./check/downloadlinkchecker.sh $secibuildtoken"
    - "url=https://git.rwth-aachen.de/monticore/languages/od/-/blob/master/src/main/grammars/de/monticore/OD4Report.md"
    - "./check/mdlinkcheck.sh -url $url -t $secibuildtoken"
  only:
    - master
