# (c) https://github.com/MontiCore/monticore

image: maven:3.5.4-jdk-8-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode"

cache:
  paths:
    - .gradle/wrapper
  key: ${CI_COMMIT_REF_SLUG}

before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - deploy
  - check

build:
  stage: build
  script:
    - "./gradlew assemble --refresh-dependencies $GRADLE_OPTS $ARGS1"
  artifacts:
    paths:
      - "."
    expire_in: 1 week

test:
  stage: test
  dependencies:
    - build
  script:
    - "./gradlew check $GRADLE_OPTS $ARGS2"

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - "./gradlew publish $GRADLE_OPTS $ARGS3 -PmavenPassword=$password -PmavenUser=$username"
  only:
    - master
    - dev

checkMDLinks:
  stage: check
  dependencies:
    - test
  script:
    - "curl --location --header \"PRIVATE-TOKEN: $secibuildtoken\" \"https://git.rwth-aachen.de/api/v4/projects/monticore%2Fmdlinkchecker/jobs/artifacts/master/raw/target/libs/MDLinkCheckerCLI.jar?job=build\" --output MDLinkCheckerCLI.jar"
    - "url=https://git.rwth-aachen.de/monticore/languages/od/-/tree/master"
    - "linkCheckRes=$(java -jar MDLinkCheckerCLI.jar -url $url -t $secibuildtoken -p)"
    - "echo \"$linkCheckRes\""
    - "if [[ $linkCheckRes == *\"ERROR\"* ]]; then exit 1; fi"
  only:
    - master
