@startuml
note "OD" as tag #white
object "__alice:Person__" as alice {
  age = 29 
}
object "__bob:Person__" as bob {
  nicknames = "Bob""Bobby""Robert"
  cars = tiger
}
alice <--> bob : married
object "____bmw_anonymous_1:BMW__" as __bmw_anonymous_1 {
  bought = 2020-01-05 15:30:00
  color = BLUE
}
object "__tiger:Jaguar__" as tiger {
  bought = 2000/01/05 15:00:00
  color = RED
  length = 5.3
}
alice *-->  "cars" __bmw_anonymous_1
alice *-->  "cars" tiger
@enduml